/*
 * defines.h
 *
 *  Created on: Jul 1, 2020
 *      Author: daandegroot
 */

#ifndef INC_DEFINES_H_
#define INC_DEFINES_H_

#define OPTIMIZE_ROM_INIT 1


#define TIM2_RELOAD_VALUE		(2232)


#define COMMON0_PORT		GPIOA
#define COMMON0_PIN			GPIO_PIN_2

#define COMMON1_PORT		GPIOA
#define COMMON1_PIN			GPIO_PIN_1

#define COMMON2_PORT		GPIOA
#define COMMON2_PIN			GPIO_PIN_3


#define SEGMENT0_PORT		GPIOD
#define SEGMENT0_PIN		GPIO_PIN_2

#define SEGMENT1_PORT		GPIOC
#define SEGMENT1_PIN		GPIO_PIN_7

#define SEGMENT2_PORT		GPIOD
#define SEGMENT2_PIN		GPIO_PIN_3

#define SEGMENT3_PORT		GPIOC
#define SEGMENT3_PIN		GPIO_PIN_6

#define SEGMENT4_PORT		GPIOC
#define SEGMENT4_PIN		GPIO_PIN_5

#define SEGMENT5_PORT		GPIOB
#define SEGMENT5_PIN		GPIO_PIN_4

#define SEGMENT6_PORT		GPIOB
#define SEGMENT6_PIN		GPIO_PIN_5


#define LED_R_PORT			GPIOC
#define LED_R_PIN			GPIO_PIN_4

#define LED_IR_PORT			GPIOC
#define LED_IR_PIN			GPIO_PIN_3


#define ADC_IN_PORT			GPIOD
#define ADC_IN_PIN			GPIO_PIN_6

#define ADC_FB_PORT			GPIOD
#define ADC_FB_PIN			GPIO_PIN_4

#endif /* INC_DEFINES_H_ */
